language: c
compiler:
  - gcc
build:
  ci:
    - shippable_retry sudo apt-get -y -qq update
    - shippable_retry sudo apt-get -y -qq install --no-install-recommends qt5-default libqt5webkit5-dev libqt5x11extras5-dev libarchive-dev libxcb-keysyms1-dev
    - qmake
    - make
